services:
  - type: web
    name: cayenne-finder
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.7"
